### ISSUE TITLE
Class pyNASA has no attribute 'outgassing'

### ISSUE THREAD

**Issue by pcuellar** [bmtgoncalves/pyNASA#4]
Running the basic case here https://bmtgoncalves.github.io/pyNASA/ shows the following error. I already moved resources.json to the pyNASA folder

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39)
 [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
 Type "help", "copyright", "credits" or "license" for more information.

>>> `from pyNASA import pyNASA
>>> nasa = pyNASA
>>> data = nasa.outgassing()

>>> Traceback (most recent call last):
>>> File "", line 1, in
>>> AttributeError: class pyNASA has no attribute 'outgassing'`

Initializing the class as 'PyNASA()' shows a 'not defined' error:

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyNASA import pyNASA
>>> nasa = PyNASA()

>>> Traceback (most recent call last):
>>> File "<stdin>", line 1, in <module>
>>> NameError: name 'PyNASA' is not defined`

**Comment by kinow** [comment]
Not sure if related to your Python version, but it works for me on Anaconda Python 3, Ubuntu 16.04.2.

```
from pyNASA import pyNASA
nasa = pyNASA()
data = nasa.outgassing()
from pprint import pprint as pp
pp(data)
category cure  cvcm        id                material_usage   mfr  \
0           12  NaN  0.00  GSC33214                     CLICKBOND   CLB   
1           12  NaN  0.00  GSC33217                     CLICKBOND   CLB   
2            6  NaN  0.05  GSC32950              BLANKET MATERIAL   SCH   
3           15  NaN  0.13  GSC34174                         ORING   PRS   
....
```

**Comment by pcuellar** [comment]
Thanks @kinow ! Just tried with Python 3.4.5 |Anaconda 4.3.0 (x86_64) and it worked
